# Generated by Django 3.0 on 2021-02-22 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('value', models.IntegerField()),
                ('level', models.IntegerField(null=True)),
                ('image', models.ImageField(upload_to='adpack-image/')),
                ('perday_revenue', models.FloatField(null=True)),
                ('expiration_day', models.IntegerField(default=60, null=True)),
                ('affiliate_earn', models.FloatField(null=True)),
                ('total_return', models.FloatField(null=True)),
                ('max_buy', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdraw_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(max_length=40)),
                ('amount', models.FloatField()),
                ('payment_done', models.BooleanField(default=False)),
                ('payment_error', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user withdraw requests',
                'verbose_name_plural': 'user withdraw requests',
            },
        ),
        migrations.CreateModel(
            name='send_money_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sent_to', models.EmailField(max_length=254)),
                ('sent_amount', models.FloatField()),
                ('sent_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='rocket_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_number', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user rocket numbers',
                'verbose_name_plural': 'user rocket numbers',
            },
        ),
        migrations.CreateModel(
            name='refer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.IntegerField(blank=True, null=True)),
                ('refer_earn', models.FloatField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pm_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_account', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user perfectMoney accounts',
                'verbose_name_plural': 'user perfectMoney accounts',
            },
        ),
        migrations.CreateModel(
            name='nagad_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nagad_number', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user nagad numbers',
                'verbose_name_plural': 'user nagad numbers',
            },
        ),
        migrations.CreateModel(
            name='deposit_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('method', models.CharField(default='PerfectMoney', max_length=40)),
                ('amount', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user deposit history',
                'verbose_name_plural': 'user deposit history',
            },
        ),
        migrations.CreateModel(
            name='bought_adpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField()),
                ('total_quantity', models.IntegerField()),
                ('adpack_totalreturn', models.FloatField()),
                ('everyday_revenue', models.FloatField()),
                ('affiliate_commission', models.FloatField()),
                ('total_price', models.FloatField()),
                ('bought_adpacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.adpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bkash_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bkash_number', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user bkash numbers',
                'verbose_name_plural': 'user bkash numbers',
            },
        ),
        migrations.CreateModel(
            name='bank_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=60, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=40, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=40, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=30, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=40, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user bank accounts',
                'verbose_name_plural': 'user bank accounts',
            },
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField(default=0.0, max_length=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='agent_accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_email', models.EmailField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user agent accounts',
                'verbose_name_plural': 'user agent accounts',
            },
        ),
        migrations.CreateModel(
            name='adpack_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('today_revenue', models.FloatField()),
                ('bought_adpack_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.bought_adpack')),
            ],
        ),
    ]
