# Generated by Django 3.0 on 2021-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_partnershipplans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipplans',
            name='package',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('royal', 'Royal')], max_length=150),
        ),
    ]
