# Generated by Django 3.0 on 2021-02-24 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20210224_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InvestmentPlans')),
                ('partnership_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.PartnershipPlans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
