# Generated by Django 3.0 on 2021-02-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_purchasedpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackage',
            name='investment_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.InvestmentPlans'),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='partnership_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.PartnershipPlans'),
        ),
    ]
