# Generated by Django 3.0 on 2021-02-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210225_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplans',
            name='package',
            field=models.CharField(choices=[('starter', 'Starter'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('platinum diamond titanium', 'Platinum Diamond Titanium'), ('diamond', 'Diamond'), ('vip', 'VIP')], max_length=150),
        ),
    ]
