# Generated by Django 3.0 on 2021-02-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210225_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplans',
            name='package',
            field=models.CharField(choices=[('starter', 'Starter'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('titanium', 'Titanium'), ('diamond', 'Diamond'), ('vip', 'VIP')], max_length=150),
        ),
    ]
