# Generated by Django 3.0 on 2021-02-28 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210226_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='end_package',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='package_start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
