# Generated by Django 3.0 on 2021-02-28 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_purchasedpackage_invest_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedpackage',
            name='last_benefit_date',
        ),
    ]
