# Generated by Django 3.0 on 2021-02-28 09:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_purchasedpackage_last_benefit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='last_benefit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 9, 27, 11, 311244, tzinfo=utc), null=True),
        ),
    ]
