# Generated by Django 3.0 on 2021-02-28 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_purchasedpackage_last_benefit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUserNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=1500)),
            ],
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='last_benefit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 9, 51, 22, 506898, tzinfo=utc), null=True),
        ),
    ]
