# Generated by Django 3.0 on 2021-02-28 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0016_auto_20210228_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackage',
            name='last_benefit_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 28, 13, 1, 32, 884114, tzinfo=utc), null=True),
        ),
        migrations.CreateModel(
            name='FranchiseWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.BooleanField(default=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
