# Generated by Django 3.0 on 2021-02-28 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210228_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedpackage',
            name='last_benefit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
