# Generated by Django 3.0 on 2021-03-01 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210301_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchisewithdraw',
            name='flag',
        ),
        migrations.AddField(
            model_name='franchisewithdraw',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='franchisewithdraw',
            name='payment_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchisewithdraw',
            name='payment_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchisewithdraw',
            name='payment_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='franchisewithdraw',
            name='amount',
            field=models.FloatField(),
        ),
    ]
