# Generated by Django 3.0 on 2021-03-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210301_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchisewithdraw',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
