# Generated by Django 3.0 on 2021-03-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210301_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisewithdraw',
            name='payment_method',
            field=models.CharField(blank=True, default='not', max_length=50, null=True),
        ),
    ]
