# Generated by Django 3.0 on 2021-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
