# Generated by Django 3.0 on 2021-03-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210301_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban',
            field=models.BooleanField(default=False),
        ),
    ]
